<?php
declare(strict_types=1); require __DIR__.'/config.php'; header('Content-Type: application/json; charset=utf-8');
function reply($x,int $code=200): never { http_response_code($code); echo json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); exit; }
function body(): array { return json_decode((string)file_get_contents('php://input'),true) ?: []; }
function run_cmd(array $parts): array { $cmd=implode(' ',array_map('escapeshellarg',$parts)).' 2>&1'; exec($cmd,$out,$code); return ['ok'=>$code===0,'code'=>$code,'output'=>implode("\n",$out)]; }
$action=$_GET['action']??'status';
if($action==='status') { $sources=[]; foreach(glob(LEXICON_ROOT.'/sources/*.json') as $f){$s=json_read($f);$name=basename((string)($s['path']??''));$p=runtime('sources/'.$name);$sources[]=['id'=>$s['id']??basename($f,'.json'),'file'=>$name,'present'=>is_file($p),'size'=>is_file($p)?filesize($p):null,'blob_sha'=>$s['blob_sha']??null];} $cand=json_read(runtime('build/safety/candidates.json')); $dec=json_read(LEXICON_ROOT.'/decisions/safety.json'); reply(['ok'=>true,'sources'=>$sources,'candidates'=>$cand['term_count']??0,'decisions'=>count($dec['decisions']??[])]); }
if($action==='candidates') { $doc=json_read(runtime('build/safety/candidates.json')); $q=mb_strtolower(trim((string)($_GET['q']??''))); $terms=$doc['terms']??[]; if($q!=='') $terms=array_values(array_filter($terms,fn($t)=>str_contains(mb_strtolower(($t['term']??'').' '.implode(' ',$t['aliases']??[])),$q))); reply(['ok'=>true,'term_count'=>count($terms),'terms'=>array_slice($terms,0,500)]); }
if($action==='save') { if($_SERVER['REQUEST_METHOD']!=='POST') reply(['ok'=>false,'error'=>'POST required'],405); $b=body(); $valid=['irrelevant','contextual_safe','contextual_review','explicit_unsafe']; $term=trim((string)($b['term']??'')); $class=(string)($b['classification']??''); if($term===''||!in_array($class,$valid,true)) reply(['ok'=>false,'error'=>'invalid decision'],400); $path=LEXICON_ROOT.'/decisions/safety.json'; $doc=json_read($path); $items=$doc['decisions']??[]; $new=['term'=>$term,'classification'=>$class,'category'=>($b['category']??'')?:null,'curated'=>true,'review'=>['reviewed_at'=>date(DATE_ATOM),'note'=>trim((string)($b['note']??''))]]; $found=false; foreach($items as &$d){if(($d['term']??'')===$term){$d=$new;$found=true;break;}} unset($d); if(!$found)$items[]=$new; usort($items,fn($a,$b)=>strcmp($a['term'],$b['term'])); $doc['decisions']=$items; json_write_atomic($path,$doc); reply(['ok'=>true]); }
if($action==='pipeline') { if($_SERVER['REQUEST_METHOD']!=='POST') reply(['ok'=>false,'error'=>'POST required'],405); $build=runtime('build/safety'); @mkdir($build,0770,true); $a=run_cmd([PYTHON,LEXICON_ROOT.'/import.py','safety','--input-dir',runtime('sources'),'--output',$build.'/normalized.json']); if(!$a['ok'])reply($a,500); $b=run_cmd([PYTHON,LEXICON_ROOT.'/discover.py','safety','--normalized',$build.'/normalized.json','--output-dir',$build]); if(!$b['ok'])reply($b,500); reply(['ok'=>true,'import'=>$a,'discover'=>$b]); }
reply(['ok'=>false,'error'=>'unknown action'],404);
